//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "CommentView.xaml.h"

void ::Reddit::CommentView::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///CommentView.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::CommentView::CommentView_obj1_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::TreeViewControl::TreeNode>
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
            ::Platform::WeakReference converterLookupRoot;
public:
    CommentView_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 1: // CommentView.xaml line 73
                this->obj1 = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void ResetTemplate()
    {
    }

    int ProcessBindings(::Windows::UI::Xaml::Controls::ContainerContentChangingEventArgs^ args)
    {
        int nextPhase = -1;
        switch(args->Phase)
        {
            case 0:
                nextPhase = -1;
                this->SetDataRoot(static_cast<::TreeViewControl::TreeNode^>(args->Item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    safe_cast<::Windows::UI::Xaml::FrameworkElement^>(args->ItemContainer->ContentTemplateRoot)->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
        }
        this->Update_((::TreeViewControl::TreeNode^) args->Item, (1 << args->Phase));
        return nextPhase;
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::FrameworkElement^ rootElement)
    {
        this->converterLookupRoot = rootElement;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        if (this->localResources == nullptr)
        {
            this->localResources = this->converterLookupRoot.Resolve<::Windows::UI::Xaml::FrameworkElement>()->Resources;
            this->converterLookupRoot = nullptr;
            }
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj1;

    // Update methods for each path node used in binding steps.
    void Update_(::TreeViewControl::TreeNode^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Depth(obj->Depth, phase);
            }
        }
    }
    void Update_Depth(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 73
            if (this->obj1 != nullptr)
            {
                ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_FrameworkElement_Margin(this->obj1.Resolve<::Windows::UI::Xaml::Controls::HyperlinkButton>(), safe_cast<::Windows::UI::Xaml::Thickness>(this->LookupConverter("IntToIndConverter")->Convert(obj, ::Windows::UI::Xaml::Thickness::typeid, nullptr, nullptr)));
            }
        }
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::CommentView::CommentView_obj2_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::TreeViewControl::TreeNode>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
            ::Platform::WeakReference converterLookupRoot;
public:
    CommentView_obj2_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~CommentView_obj2_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 2: // CommentView.xaml line 22
                this->obj2 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 3: // CommentView.xaml line 36
                this->obj3 = safe_cast<::Windows::UI::Xaml::Controls::RichTextBlock^>(__target);
                break;
            case 4: // CommentView.xaml line 39
                this->obj4 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
                break;
            case 5: // CommentView.xaml line 44
                this->obj5 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
                break;
            case 6: // CommentView.xaml line 49
                this->obj6 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
                this->obj6->RegisterPropertyChangedCallback(::Windows::UI::Xaml::Controls::Primitives::ToggleButton::IsCheckedProperty,
                    ref new ::Windows::UI::Xaml::DependencyPropertyChangedCallback( 
                        [this] (::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                (safe_cast<::account::CommentUWPitem^>(this->GetDataRoot()->Data))->saved = this->obj6->IsChecked ? this->obj6->IsChecked->Value : false;
                            }
                        }));
                break;
            case 7: // CommentView.xaml line 57
                this->obj7 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                break;
            case 8: // CommentView.xaml line 59
                this->obj8 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
                this->obj8->RegisterPropertyChangedCallback(::Windows::UI::Xaml::Controls::Primitives::ToggleButton::IsCheckedProperty,
                    ref new ::Windows::UI::Xaml::DependencyPropertyChangedCallback( 
                        [this] (::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                this->GetDataRoot()->IsExpanded = safe_cast<::Platform::Boolean>(this->LookupConverter("inverseBoolConverter")->ConvertBack(this->obj8->IsChecked, ::Platform::Boolean::typeid, nullptr, nullptr));
                            }
                        }));
                break;
            case 9: // CommentView.xaml line 30
                this->obj9 = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
                break;
            case 10: // CommentView.xaml line 32
                this->obj10 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void ResetTemplate()
    {
        ReleaseAllListeners();
    }

    int ProcessBindings(::Windows::UI::Xaml::Controls::ContainerContentChangingEventArgs^ args)
    {
        int nextPhase = -1;
        switch(args->Phase)
        {
            case 0:
                nextPhase = -1;
                this->SetDataRoot(static_cast<::TreeViewControl::TreeNode^>(args->Item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    safe_cast<::Windows::UI::Xaml::FrameworkElement^>(args->ItemContainer->ContentTemplateRoot)->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
        }
        this->Update_((::TreeViewControl::TreeNode^) args->Item, (1 << args->Phase));
        return nextPhase;
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::FrameworkElement^ rootElement)
    {
        this->converterLookupRoot = rootElement;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        if (this->localResources == nullptr)
        {
            this->localResources = this->converterLookupRoot.Resolve<::Windows::UI::Xaml::FrameworkElement>()->Resources;
            this->converterLookupRoot = nullptr;
            }
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj2;
    ::Windows::UI::Xaml::Controls::RichTextBlock^ obj3;
    ::Windows::UI::Xaml::Controls::AppBarToggleButton^ obj4;
    ::Windows::UI::Xaml::Controls::AppBarToggleButton^ obj5;
    ::Windows::UI::Xaml::Controls::AppBarToggleButton^ obj6;
    ::Windows::UI::Xaml::Controls::AppBarButton^ obj7;
    ::Windows::UI::Xaml::Controls::AppBarToggleButton^ obj8;
    ::Windows::UI::Xaml::Controls::HyperlinkButton^ obj9;
    ::Windows::UI::Xaml::Documents::Run^ obj10;
    
    // Fields for binding tracking.
    ::Platform::WeakReference cachePC_;
    ::Windows::UI::Xaml::Data::INotifyPropertyChanged^ cachePC_Data_Cast_Data_To_CommentUWPitem = nullptr;
    ::Windows::Foundation::EventRegistrationToken tokenPC_;
    ::Windows::Foundation::EventRegistrationToken tokenPC_Data_Cast_Data_To_CommentUWPitem;

    // Update methods for each path node used in binding steps.
    void Update_(::TreeViewControl::TreeNode^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, this->cachePC_, &tokenPC_);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Depth(obj->Depth, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Data(obj->Data, phase);
                this->Update_IsExpanded(obj->IsExpanded, phase);
            }
        }
        else
        {
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->UpdateFallback_Data(phase);
            }
        }
    }
    void Update_Depth(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 22
            if (this->obj2 != nullptr)
            {
                ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_FrameworkElement_Margin(this->obj2.Resolve<::Windows::UI::Xaml::Controls::Grid>(), safe_cast<::Windows::UI::Xaml::Thickness>(this->LookupConverter("IntToIndConverter")->Convert(obj, ::Windows::UI::Xaml::Thickness::typeid, nullptr, nullptr)));
            }
        }
    }
    void Update_Data(::Platform::Object^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Data_Cast_Data_To_CommentUWPitem(safe_cast<::account::CommentUWPitem^>(obj), phase);
            }
        }
        else
        {
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->UpdateFallback_Data_Cast_Data_To_CommentUWPitem(phase);
            }
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem(::account::CommentUWPitem^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, &this->cachePC_Data_Cast_Data_To_CommentUWPitem, &tokenPC_Data_Cast_Data_To_CommentUWPitem);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Data_Cast_Data_To_CommentUWPitem_htmltext(obj->htmltext, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Data_Cast_Data_To_CommentUWPitem_Liked(obj->Liked, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Data_Cast_Data_To_CommentUWPitem_changeupvote(obj->changeupvote, phase);
                this->Update_Data_Cast_Data_To_CommentUWPitem_changedownvote(obj->changedownvote, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Data_Cast_Data_To_CommentUWPitem_saved(obj->saved, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Data_Cast_Data_To_CommentUWPitem_isMine(obj->isMine, phase);
                this->Update_Data_Cast_Data_To_CommentUWPitem_author(obj->author, phase);
                this->Update_Data_Cast_Data_To_CommentUWPitem_score(obj->score, phase);
            }
        }
        else
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->UpdateFallback_Data_Cast_Data_To_CommentUWPitem_author(phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->UpdateFallback_Data_Cast_Data_To_CommentUWPitem_score(phase);
            }
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_htmltext(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 36
            ::XamlBindingInfo::XamlBindingSetters::Set_html2xaml_Properties_Html(this->obj3, obj, nullptr);
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_Liked(::Platform::IBox<::Platform::Boolean>^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // CommentView.xaml line 39
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj4, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("upvoteconverter")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
            // CommentView.xaml line 44
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj5, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("downvoteconverter")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_changeupvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 39
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj4, obj, nullptr);
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_changedownvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 44
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj5, obj, nullptr);
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_saved(::Platform::Boolean obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // CommentView.xaml line 49
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj6, obj, nullptr);
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_isMine(::Platform::Boolean obj, int phase)
    {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Data_Cast_Data_To_CommentUWPitem_isMine_Cast_isMine_To_Visibility(obj ? ::Windows::UI::Xaml::Visibility::Visible : ::Windows::UI::Xaml::Visibility::Collapsed, phase);
            }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_isMine_Cast_isMine_To_Visibility(::Windows::UI::Xaml::Visibility obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 57
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_UIElement_Visibility(this->obj7, obj);
        }
    }
    void Update_IsExpanded(::Platform::Boolean obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // CommentView.xaml line 59
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj8, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("inverseBoolConverter")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_author(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 30
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_ContentControl_Content(this->obj9, obj, nullptr);
        }
    }
    void Update_Data_Cast_Data_To_CommentUWPitem_score(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 32
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Documents_Run_Text(this->obj10, obj.ToString(), nullptr);
        }
    }

    void UpdateFallback_Data(int phase)
    {
        this->UpdateFallback_Data_Cast_Data_To_CommentUWPitem(phase);
    }

    void UpdateFallback_Data_Cast_Data_To_CommentUWPitem(int phase)
    {
        this->UpdateFallback_Data_Cast_Data_To_CommentUWPitem_author(phase);
        this->UpdateFallback_Data_Cast_Data_To_CommentUWPitem_score(phase);
    }

    void UpdateFallback_Data_Cast_Data_To_CommentUWPitem_author(int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 30
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_ContentControl_Content(this->obj9, (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, "username"), nullptr);
        }
    }

    void UpdateFallback_Data_Cast_Data_To_CommentUWPitem_score(int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // CommentView.xaml line 32
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Documents_Run_Text(this->obj10, "30", nullptr);
        }
    }

    virtual void ReleaseAllListeners() override
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, this->cachePC_, &tokenPC_);
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, &this->cachePC_Data_Cast_Data_To_CommentUWPitem, &tokenPC_Data_Cast_Data_To_CommentUWPitem);
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
        if (this->GetDataRoot() != nullptr && this->GetDataRoot()->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::TreeViewControl::TreeNode^ obj = safe_cast<::TreeViewControl::TreeNode^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_Data(obj->Data, DATA_CHANGED);
                    this->Update_IsExpanded(obj->IsExpanded, DATA_CHANGED);
                }
                else
                {
                    this->UpdateFallback_Data(DATA_CHANGED);
                }
            }
            else if (propName == "Data")
            {
                if (obj != nullptr)
                {
                    this->Update_Data(obj->Data, DATA_CHANGED);
                }
                else
                {
                    this->UpdateFallback_Data(DATA_CHANGED);
                }
            }
            else if (propName == "IsExpanded")
            {
                if (obj != nullptr)
                {
                    this->Update_IsExpanded(obj->IsExpanded, DATA_CHANGED);
                }
            }
        }
        if (cachePC_Data_Cast_Data_To_CommentUWPitem != nullptr && cachePC_Data_Cast_Data_To_CommentUWPitem->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::account::CommentUWPitem^ obj = safe_cast<::account::CommentUWPitem^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_Data_Cast_Data_To_CommentUWPitem_Liked(obj->Liked, DATA_CHANGED);
                    this->Update_Data_Cast_Data_To_CommentUWPitem_saved(obj->saved, DATA_CHANGED);
                }
            }
            else if (propName == "Liked")
            {
                if (obj != nullptr)
                {
                    this->Update_Data_Cast_Data_To_CommentUWPitem_Liked(obj->Liked, DATA_CHANGED);
                }
            }
            else if (propName == "saved")
            {
                if (obj != nullptr)
                {
                    this->Update_Data_Cast_Data_To_CommentUWPitem_saved(obj->saved, DATA_CHANGED);
                }
            }
        }
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }
};

void ::Reddit::CommentView::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 11:
        {
            this->commentTree = safe_cast<::TreeViewControl::TreeView^>(__target);
            (safe_cast<::TreeViewControl::TreeView^>(this->commentTree))->ChoosingItemContainer += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::ListViewBase^, ::Windows::UI::Xaml::Controls::ChoosingItemContainerEventArgs^>(this, (void (::Reddit::CommentView::*)
                (::Windows::UI::Xaml::Controls::ListViewBase^, ::Windows::UI::Xaml::Controls::ChoosingItemContainerEventArgs^))&CommentView::commentTree_ChoosingItemContainer);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Reddit::CommentView::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1: // CommentView.xaml line 73
            {
                ::Windows::UI::Xaml::Controls::HyperlinkButton^ element1 = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
                CommentView_obj1_Bindings* objBindings = new CommentView_obj1_Bindings();
                objBindings->SetDataRoot(element1->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element1);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element1, bindings);
            }
            break;
        case 2: // CommentView.xaml line 22
            {
                ::Windows::UI::Xaml::Controls::Grid^ element2 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                CommentView_obj2_Bindings* objBindings = new CommentView_obj2_Bindings();
                objBindings->SetDataRoot(element2->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element2);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element2, bindings);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


