//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MyResources.xaml.h"

void ::Reddit::MyResources::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MyResources.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::MyResources::MyResources_obj7_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::account::subpostUWP, ::XamlBindingInfo::XamlBindingTrackingBase>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
public:
    MyResources_obj7_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~MyResources_obj7_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 7: // MyResources.xaml line 201
                this->obj7 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 8: // MyResources.xaml line 211
                this->obj8 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                break;
            case 9: // MyResources.xaml line 217
                this->obj9 = safe_cast<::ExpanderControl::Expander^>(__target);
                break;
            case 11: // MyResources.xaml line 232
                this->obj11 = safe_cast<::Reddit::AppBarToggleColoredButton^>(__target);
                break;
            case 12: // MyResources.xaml line 238
                this->obj12 = safe_cast<::Reddit::AppBarToggleColoredButton^>(__target);
                break;
            case 13: // MyResources.xaml line 243
                this->obj13 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
                this->obj13->RegisterPropertyChangedCallback(::Windows::UI::Xaml::Controls::Primitives::ToggleButton::IsCheckedProperty,
                    ref new ::Windows::UI::Xaml::DependencyPropertyChangedCallback( 
                        [this] (::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                this->GetDataRoot()->saved = this->obj13->IsChecked ? this->obj13->IsChecked->Value : false;
                            }
                        }));
                break;
            case 15: // MyResources.xaml line 255
                this->obj15 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                break;
            case 16: // MyResources.xaml line 246
                this->obj16 = safe_cast<::Reddit::reportFlyout^>(__target);
                break;
            case 17: // MyResources.xaml line 224
                this->obj17 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 20: // MyResources.xaml line 227
                this->obj20 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 21: // MyResources.xaml line 227
                this->obj21 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 22: // MyResources.xaml line 224
                this->obj22 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 23: // MyResources.xaml line 224
                this->obj23 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 24: // MyResources.xaml line 221
                this->obj24 = safe_cast<::Reddit::EXplaceHolder^>(__target);
                break;
            case 25: // MyResources.xaml line 214
                this->obj25 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 26: // MyResources.xaml line 214
                this->obj26 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        ReleaseAllListeners();
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::subpostUWP^>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj7.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::subpostUWP^) item, 1 << phase);
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::ResourceDictionary^ resources)
    {
        this->localResources = resources;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj7;
    ::Windows::UI::Xaml::Controls::Button^ obj8;
    ::ExpanderControl::Expander^ obj9;
    ::Reddit::AppBarToggleColoredButton^ obj11;
    ::Reddit::AppBarToggleColoredButton^ obj12;
    ::Windows::UI::Xaml::Controls::AppBarToggleButton^ obj13;
    ::Windows::UI::Xaml::Controls::AppBarButton^ obj15;
    ::Reddit::reportFlyout^ obj16;
    ::Windows::UI::Xaml::Documents::Run^ obj17;
    ::Windows::UI::Xaml::Documents::Run^ obj20;
    ::Windows::UI::Xaml::Documents::Run^ obj21;
    ::Windows::UI::Xaml::Documents::Run^ obj22;
    ::Windows::UI::Xaml::Documents::Run^ obj23;
    ::Reddit::EXplaceHolder^ obj24;
    ::Windows::UI::Xaml::Documents::Run^ obj25;
    ::Windows::UI::Xaml::Documents::Run^ obj26;
    
    // Fields for binding tracking.
    ::Platform::WeakReference cachePC_;
    ::Windows::Foundation::EventRegistrationToken tokenPC_;

    // Update methods for each path node used in binding steps.
    void Update_(::account::subpostUWP^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, this->cachePC_, &tokenPC_);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_thumbnail(obj->thumbnail, phase);
                this->Update_previewCommand(obj->previewCommand, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_contentType(obj->contentType, phase);
                this->Update_Liked(obj->Liked, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changeupvote(obj->changeupvote, phase);
                this->Update_changedownvote(obj->changedownvote, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_saved(obj->saved, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_subreddit(obj->subreddit, phase);
                this->Update_CreatedString(obj->CreatedString, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_ScoreText(obj->ScoreText, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_num_comments(obj->num_comments, phase);
                this->Update_author(obj->author, phase);
                this->Update_Title(obj->Title, phase);
                this->Update_domain(obj->domain, phase);
            }
        }
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 255
            Set_Windows_UI_Xaml_FrameworkElement_Tag(this->obj15, obj, nullptr);
            // MyResources.xaml line 221
            Set_Reddit_EXplaceHolder_post(this->obj24, obj, nullptr);
        }
    }
    void Update_thumbnail(::Windows::UI::Xaml::FrameworkElement^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 211
            Set_Windows_UI_Xaml_Controls_ContentControl_Content(this->obj8, obj, nullptr);
        }
    }
    void Update_previewCommand(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 211
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj8, obj, nullptr);
        }
    }
    void Update_contentType(::account::postContentType obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 217
            Set_Windows_UI_Xaml_UIElement_Visibility(this->obj9, safe_cast<::Windows::UI::Xaml::Visibility>(this->LookupConverter("prevConv")->Convert(obj, ::Windows::UI::Xaml::Visibility::typeid, "self", nullptr)));
        }
    }
    void Update_Liked(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 232
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj11, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("upvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
            // MyResources.xaml line 238
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj12, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("downvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_changeupvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 232
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj11, obj, nullptr);
        }
    }
    void Update_changedownvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 238
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj12, obj, nullptr);
        }
    }
    void Update_saved(::Platform::Boolean obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 243
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj13, obj, nullptr);
        }
    }
    void Update_subreddit(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 246
            Set_Reddit_reportFlyout_subreddit(this->obj16, obj, nullptr);
            // MyResources.xaml line 224
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj22, obj, nullptr);
        }
    }
    void Update_CreatedString(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 224
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj17, obj, nullptr);
        }
    }
    void Update_ScoreText(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 227
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj20, obj, nullptr);
        }
    }
    void Update_num_comments(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 227
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj21, obj.ToString(), nullptr);
        }
    }
    void Update_author(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 224
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj23, obj, nullptr);
        }
    }
    void Update_Title(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 214
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj25, obj, nullptr);
        }
    }
    void Update_domain(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 214
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj26, obj, nullptr);
        }
    }

    virtual void ReleaseAllListeners() override
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, this->cachePC_, &tokenPC_);
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
        if (this->GetDataRoot() != nullptr && this->GetDataRoot()->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::account::subpostUWP^ obj = safe_cast<::account::subpostUWP^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_contentType(obj->contentType, DATA_CHANGED);
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                    this->Update_saved(obj->saved, DATA_CHANGED);
                    this->Update_ScoreText(obj->ScoreText, DATA_CHANGED);
                }
            }
            else if (propName == "contentType")
            {
                if (obj != nullptr)
                {
                    this->Update_contentType(obj->contentType, DATA_CHANGED);
                }
            }
            else if (propName == "Liked")
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                }
            }
            else if (propName == "saved")
            {
                if (obj != nullptr)
                {
                    this->Update_saved(obj->saved, DATA_CHANGED);
                }
            }
            else if (propName == "ScoreText")
            {
                if (obj != nullptr)
                {
                    this->Update_ScoreText(obj->ScoreText, DATA_CHANGED);
                }
            }
        }
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }
    static void Set_Windows_UI_Xaml_Controls_ContentControl_Content(::Windows::UI::Xaml::Controls::ContentControl^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->Content = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(::Windows::UI::Xaml::Controls::Primitives::ButtonBase^ obj, ::Windows::UI::Xaml::Input::ICommand^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Input::ICommand^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Input::ICommand::typeid, targetNullValue);
        }
        obj->Command = value;
    }
    static void Set_Windows_UI_Xaml_UIElement_Visibility(::Windows::UI::Xaml::UIElement^ obj, ::Windows::UI::Xaml::Visibility value)
    {
        obj->Visibility = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ obj, ::Platform::IBox<::Platform::Boolean>^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::IBox<::Platform::Boolean>^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::IBox<::Platform::Boolean>::typeid, targetNullValue);
        }
        obj->IsChecked = value;
    }
    static void Set_Windows_UI_Xaml_FrameworkElement_Tag(::Windows::UI::Xaml::FrameworkElement^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->Tag = value;
    }
    static void Set_Reddit_reportFlyout_subreddit(::Reddit::reportFlyout^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->subreddit = value;
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Reddit_EXplaceHolder_post(::Reddit::EXplaceHolder^ obj, ::account::subpostUWP^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::account::subpostUWP^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::account::subpostUWP::typeid, targetNullValue);
        }
        obj->post = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::MyResources::MyResources_obj27_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::account::subpostUWP, ::XamlBindingInfo::XamlBindingTrackingBase>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
public:
    MyResources_obj27_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~MyResources_obj27_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 27: // MyResources.xaml line 152
                this->obj27 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 28: // MyResources.xaml line 158
                this->obj28 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 29: // MyResources.xaml line 159
                this->obj29 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 30: // MyResources.xaml line 190
                this->obj30 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 31: // MyResources.xaml line 194
                this->obj31 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 32: // MyResources.xaml line 164
                this->obj32 = safe_cast<::Reddit::NoToggleBehaviorButton^>(__target);
                break;
            case 33: // MyResources.xaml line 176
                this->obj33 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 34: // MyResources.xaml line 177
                this->obj34 = safe_cast<::Reddit::NoToggleBehaviorButton^>(__target);
                break;
            case 35: // MyResources.xaml line 161
                this->obj35 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        ReleaseAllListeners();
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::subpostUWP^>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj27.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::subpostUWP^) item, 1 << phase);
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::ResourceDictionary^ resources)
    {
        this->localResources = resources;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj27;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj28;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj29;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj30;
    ::Windows::UI::Xaml::Documents::Run^ obj31;
    ::Reddit::NoToggleBehaviorButton^ obj32;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj33;
    ::Reddit::NoToggleBehaviorButton^ obj34;
    ::Windows::UI::Xaml::Documents::Run^ obj35;
    
    // Fields for binding tracking.
    ::Platform::WeakReference cachePC_;
    ::Windows::Foundation::EventRegistrationToken tokenPC_;

    // Update methods for each path node used in binding steps.
    void Update_(::account::subpostUWP^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, this->cachePC_, &tokenPC_);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Title(obj->Title, phase);
                this->Update_author(obj->author, phase);
                this->Update_selftext(obj->selftext, phase);
                this->Update_num_comments(obj->num_comments, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Liked(obj->Liked, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changeupvote(obj->changeupvote, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_score(obj->score, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changedownvote(obj->changedownvote, phase);
                this->Update_subreddit(obj->subreddit, phase);
            }
        }
    }
    void Update_Title(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 158
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj28, obj, nullptr);
        }
    }
    void Update_author(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 159
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj29, obj, nullptr);
        }
    }
    void Update_selftext(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 190
            Set_mdblock_mdRichProperties_MD(this->obj30, obj, nullptr);
        }
    }
    void Update_num_comments(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 194
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj31, obj.ToString(), nullptr);
        }
    }
    void Update_Liked(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 164
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj32, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("upvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
            // MyResources.xaml line 177
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj34, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("downvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_changeupvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 164
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj32, obj, nullptr);
        }
    }
    void Update_score(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 176
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj33, obj.ToString(), nullptr);
        }
    }
    void Update_changedownvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 177
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj34, obj, nullptr);
        }
    }
    void Update_subreddit(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 161
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj35, obj, nullptr);
        }
    }

    virtual void ReleaseAllListeners() override
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, this->cachePC_, &tokenPC_);
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
        if (this->GetDataRoot() != nullptr && this->GetDataRoot()->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::account::subpostUWP^ obj = safe_cast<::account::subpostUWP^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
            else if (propName == "Liked")
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                }
            }
            else if (propName == "score")
            {
                if (obj != nullptr)
                {
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
        }
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_mdblock_mdRichProperties_MD(::Windows::UI::Xaml::UIElement^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        ::mdblock::mdRichProperties::SetMD(obj, value);
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ obj, ::Platform::IBox<::Platform::Boolean>^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::IBox<::Platform::Boolean>^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::IBox<::Platform::Boolean>::typeid, targetNullValue);
        }
        obj->IsChecked = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(::Windows::UI::Xaml::Controls::Primitives::ButtonBase^ obj, ::Windows::UI::Xaml::Input::ICommand^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Input::ICommand^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Input::ICommand::typeid, targetNullValue);
        }
        obj->Command = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::MyResources::MyResources_obj36_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::account::subpostUWP, ::XamlBindingInfo::XamlBindingTrackingBase>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
public:
    MyResources_obj36_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~MyResources_obj36_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 36: // MyResources.xaml line 116
                this->obj36 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 37: // MyResources.xaml line 122
                this->obj37 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 38: // MyResources.xaml line 123
                this->obj38 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 39: // MyResources.xaml line 133
                this->obj39 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                break;
            case 40: // MyResources.xaml line 146
                this->obj40 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 41: // MyResources.xaml line 140
                this->obj41 = safe_cast<::Windows::UI::Xaml::Shapes::Path^>(__target);
                break;
            case 42: // MyResources.xaml line 137
                this->obj42 = safe_cast<::Windows::UI::Xaml::Media::Imaging::BitmapImage^>(__target);
                break;
            case 43: // MyResources.xaml line 128
                this->obj43 = safe_cast<::Reddit::NoToggleBehaviorButton^>(__target);
                break;
            case 44: // MyResources.xaml line 129
                this->obj44 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 45: // MyResources.xaml line 130
                this->obj45 = safe_cast<::Reddit::NoToggleBehaviorButton^>(__target);
                break;
            case 46: // MyResources.xaml line 125
                this->obj46 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        ReleaseAllListeners();
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::subpostUWP^>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj36.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::subpostUWP^) item, 1 << phase);
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::ResourceDictionary^ resources)
    {
        this->localResources = resources;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj36;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj37;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj38;
    ::Windows::UI::Xaml::Controls::Button^ obj39;
    ::Windows::UI::Xaml::Documents::Run^ obj40;
    ::Windows::UI::Xaml::Shapes::Path^ obj41;
    ::Windows::UI::Xaml::Media::Imaging::BitmapImage^ obj42;
    ::Reddit::NoToggleBehaviorButton^ obj43;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj44;
    ::Reddit::NoToggleBehaviorButton^ obj45;
    ::Windows::UI::Xaml::Documents::Run^ obj46;
    
    // Fields for binding tracking.
    ::Platform::WeakReference cachePC_;
    ::Windows::Foundation::EventRegistrationToken tokenPC_;

    // Update methods for each path node used in binding steps.
    void Update_(::account::subpostUWP^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, this->cachePC_, &tokenPC_);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Title(obj->Title, phase);
                this->Update_author(obj->author, phase);
                this->Update_previewCommand(obj->previewCommand, phase);
                this->Update_num_comments(obj->num_comments, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_contentType(obj->contentType, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_previewURI(obj->previewURI, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Liked(obj->Liked, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changeupvote(obj->changeupvote, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_score(obj->score, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changedownvote(obj->changedownvote, phase);
                this->Update_subreddit(obj->subreddit, phase);
            }
        }
    }
    void Update_Title(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 122
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj37, obj, nullptr);
        }
    }
    void Update_author(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 123
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj38, obj, nullptr);
        }
    }
    void Update_previewCommand(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 133
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj39, obj, nullptr);
        }
    }
    void Update_num_comments(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 146
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj40, obj.ToString(), nullptr);
        }
    }
    void Update_contentType(::account::postContentType obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 140
            Set_Windows_UI_Xaml_Shapes_Path_Data(this->obj41, safe_cast<::Windows::UI::Xaml::Media::Geometry^>(this->LookupConverter("pathdataconvz")->Convert(obj, ::Windows::UI::Xaml::Media::Geometry::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_previewURI(::Windows::Foundation::Uri^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 137
            Set_Windows_UI_Xaml_Media_Imaging_BitmapImage_UriSource(this->obj42, obj, nullptr);
        }
    }
    void Update_Liked(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 128
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj43, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("upvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
            // MyResources.xaml line 130
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj45, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("downvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_changeupvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 128
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj43, obj, nullptr);
        }
    }
    void Update_score(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 129
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj44, obj.ToString(), nullptr);
        }
    }
    void Update_changedownvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 130
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj45, obj, nullptr);
        }
    }
    void Update_subreddit(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 125
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj46, obj, nullptr);
        }
    }

    virtual void ReleaseAllListeners() override
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, this->cachePC_, &tokenPC_);
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
        if (this->GetDataRoot() != nullptr && this->GetDataRoot()->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::account::subpostUWP^ obj = safe_cast<::account::subpostUWP^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_contentType(obj->contentType, DATA_CHANGED);
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
            else if (propName == "contentType")
            {
                if (obj != nullptr)
                {
                    this->Update_contentType(obj->contentType, DATA_CHANGED);
                }
            }
            else if (propName == "Liked")
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                }
            }
            else if (propName == "score")
            {
                if (obj != nullptr)
                {
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
        }
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(::Windows::UI::Xaml::Controls::Primitives::ButtonBase^ obj, ::Windows::UI::Xaml::Input::ICommand^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Input::ICommand^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Input::ICommand::typeid, targetNullValue);
        }
        obj->Command = value;
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Shapes_Path_Data(::Windows::UI::Xaml::Shapes::Path^ obj, ::Windows::UI::Xaml::Media::Geometry^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Media::Geometry^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::Geometry::typeid, targetNullValue);
        }
        obj->Data = value;
    }
    static void Set_Windows_UI_Xaml_Media_Imaging_BitmapImage_UriSource(::Windows::UI::Xaml::Media::Imaging::BitmapImage^ obj, ::Windows::Foundation::Uri^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::Foundation::Uri^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::Foundation::Uri::typeid, targetNullValue);
        }
        obj->UriSource = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ obj, ::Platform::IBox<::Platform::Boolean>^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::IBox<::Platform::Boolean>^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::IBox<::Platform::Boolean>::typeid, targetNullValue);
        }
        obj->IsChecked = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::MyResources::MyResources_obj47_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::account::CommentUWPitem, ::XamlBindingInfo::XamlBindingTrackingBase>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
public:
    MyResources_obj47_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~MyResources_obj47_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 47: // MyResources.xaml line 65
                this->obj47 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 48: // MyResources.xaml line 79
                this->obj48 = safe_cast<::Windows::UI::Xaml::Controls::RichTextBlock^>(__target);
                break;
            case 49: // MyResources.xaml line 82
                this->obj49 = safe_cast<::Reddit::AppBarToggleColoredButton^>(__target);
                break;
            case 50: // MyResources.xaml line 87
                this->obj50 = safe_cast<::Reddit::AppBarToggleColoredButton^>(__target);
                break;
            case 51: // MyResources.xaml line 92
                this->obj51 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
                this->obj51->RegisterPropertyChangedCallback(::Windows::UI::Xaml::Controls::Primitives::ToggleButton::IsCheckedProperty,
                    ref new ::Windows::UI::Xaml::DependencyPropertyChangedCallback( 
                        [this] (::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                this->GetDataRoot()->saved = this->obj51->IsChecked ? this->obj51->IsChecked->Value : false;
                            }
                        }));
                break;
            case 52: // MyResources.xaml line 98
                this->obj52 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                break;
            case 54: // MyResources.xaml line 95
                this->obj54 = safe_cast<::Reddit::reportFlyout^>(__target);
                break;
            case 55: // MyResources.xaml line 73
                this->obj55 = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
                break;
            case 56: // MyResources.xaml line 74
                this->obj56 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        ReleaseAllListeners();
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::CommentUWPitem^>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj47.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::CommentUWPitem^) item, 1 << phase);
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::ResourceDictionary^ resources)
    {
        this->localResources = resources;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj47;
    ::Windows::UI::Xaml::Controls::RichTextBlock^ obj48;
    ::Reddit::AppBarToggleColoredButton^ obj49;
    ::Reddit::AppBarToggleColoredButton^ obj50;
    ::Windows::UI::Xaml::Controls::AppBarToggleButton^ obj51;
    ::Windows::UI::Xaml::Controls::AppBarButton^ obj52;
    ::Reddit::reportFlyout^ obj54;
    ::Windows::UI::Xaml::Controls::HyperlinkButton^ obj55;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj56;
    
    // Fields for binding tracking.
    ::Platform::WeakReference cachePC_;
    ::Windows::Foundation::EventRegistrationToken tokenPC_;

    // Update methods for each path node used in binding steps.
    void Update_(::account::CommentUWPitem^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, this->cachePC_, &tokenPC_);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_mdElements(obj->mdElements, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Liked(obj->Liked, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changeupvote(obj->changeupvote, phase);
                this->Update_changedownvote(obj->changedownvote, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_saved(obj->saved, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_isMine(obj->isMine, phase);
                this->Update_ParentSubreddit(obj->ParentSubreddit, phase);
                this->Update_author(obj->author, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_ScoreText(obj->ScoreText, phase);
            }
        }
        else
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->UpdateFallback_author(phase);
            }
        }
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 65
            if (this->obj47 != nullptr)
            {
                Set_Windows_UI_Xaml_FrameworkElement_Tag(this->obj47.Resolve<::Windows::UI::Xaml::Controls::Grid>(), obj, nullptr);
            }
        }
    }
    void Update_mdElements(::mdblock::refMDElements^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 79
            Set_mdblock_mdRichProperties_MDElements(this->obj48, obj, nullptr);
        }
    }
    void Update_Liked(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 82
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj49, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("upvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
            // MyResources.xaml line 87
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj50, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("downvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_changeupvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 82
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj49, obj, nullptr);
        }
    }
    void Update_changedownvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 87
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj50, obj, nullptr);
        }
    }
    void Update_saved(::Platform::Boolean obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 92
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj51, obj, nullptr);
        }
    }
    void Update_isMine(::Platform::Boolean obj, int phase)
    {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_isMine_Cast_isMine_To_Visibility(obj ? ::Windows::UI::Xaml::Visibility::Visible : ::Windows::UI::Xaml::Visibility::Collapsed, phase);
            }
    }
    void Update_isMine_Cast_isMine_To_Visibility(::Windows::UI::Xaml::Visibility obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 98
            Set_Windows_UI_Xaml_UIElement_Visibility(this->obj52, obj);
        }
    }
    void Update_ParentSubreddit(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 95
            Set_Reddit_reportFlyout_subreddit(this->obj54, obj, nullptr);
        }
    }
    void Update_author(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 73
            Set_Windows_UI_Xaml_Controls_ContentControl_Content(this->obj55, obj, nullptr);
        }
    }
    void Update_ScoreText(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 74
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj56, obj, nullptr);
        }
    }

    void UpdateFallback_author(int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 73
            Set_Windows_UI_Xaml_Controls_ContentControl_Content(this->obj55, (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, "username"), nullptr);
        }
    }

    virtual void ReleaseAllListeners() override
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, this->cachePC_, &tokenPC_);
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
        if (this->GetDataRoot() != nullptr && this->GetDataRoot()->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::account::CommentUWPitem^ obj = safe_cast<::account::CommentUWPitem^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                    this->Update_saved(obj->saved, DATA_CHANGED);
                    this->Update_ScoreText(obj->ScoreText, DATA_CHANGED);
                }
            }
            else if (propName == "Liked")
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                }
            }
            else if (propName == "saved")
            {
                if (obj != nullptr)
                {
                    this->Update_saved(obj->saved, DATA_CHANGED);
                }
            }
            else if (propName == "ScoreText")
            {
                if (obj != nullptr)
                {
                    this->Update_ScoreText(obj->ScoreText, DATA_CHANGED);
                }
            }
        }
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }
    static void Set_Windows_UI_Xaml_FrameworkElement_Tag(::Windows::UI::Xaml::FrameworkElement^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->Tag = value;
    }
    static void Set_mdblock_mdRichProperties_MDElements(::Windows::UI::Xaml::UIElement^ obj, ::mdblock::refMDElements^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::mdblock::refMDElements^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::mdblock::refMDElements::typeid, targetNullValue);
        }
        ::mdblock::mdRichProperties::SetMDElements(obj, value);
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ obj, ::Platform::IBox<::Platform::Boolean>^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::IBox<::Platform::Boolean>^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::IBox<::Platform::Boolean>::typeid, targetNullValue);
        }
        obj->IsChecked = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(::Windows::UI::Xaml::Controls::Primitives::ButtonBase^ obj, ::Windows::UI::Xaml::Input::ICommand^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Input::ICommand^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Input::ICommand::typeid, targetNullValue);
        }
        obj->Command = value;
    }
    static void Set_Windows_UI_Xaml_UIElement_Visibility(::Windows::UI::Xaml::UIElement^ obj, ::Windows::UI::Xaml::Visibility value)
    {
        obj->Visibility = value;
    }
    static void Set_Reddit_reportFlyout_subreddit(::Reddit::reportFlyout^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->subreddit = value;
    }
    static void Set_Windows_UI_Xaml_Controls_ContentControl_Content(::Windows::UI::Xaml::Controls::ContentControl^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->Content = value;
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
};

void ::Reddit::MyResources::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->inlineExpanderButtoning = safe_cast<::Windows::UI::Xaml::Controls::ControlTemplate^>(__target);
        }
        break;
    case 3:
        {
            this->listSelfPost = safe_cast<::Windows::UI::Xaml::DataTemplate^>(__target);
        }
        break;
    case 5:
        {
            ::Microsoft::Advertising::WinRT::UI::AdControl^ element5 = safe_cast<::Microsoft::Advertising::WinRT::UI::AdControl^>(__target);
            (safe_cast<::Microsoft::Advertising::WinRT::UI::AdControl^>(element5))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::AdControl_Loaded);
        }
        break;
    case 6:
        {
            ::Windows::UI::Xaml::Controls::RelativePanel^ element6 = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(element6))->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(this, (void (::Reddit::MyResources::*)
                (::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^))&MyResources::adcontainer_loading);
        }
        break;
    case 9:
        {
            ::ExpanderControl::Expander^ element9 = safe_cast<::ExpanderControl::Expander^>(__target);
            (safe_cast<::ExpanderControl::Expander^>(element9))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::contentExpander_Loading);
        }
        break;
    case 10:
        {
            ::Windows::UI::Xaml::Controls::TextBlock^ element10 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(element10))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::TextBlock_Loaded);
        }
        break;
    case 14:
        {
            ::Windows::UI::Xaml::Controls::AppBarToggleButton^ element14 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(element14))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::replyButton_Click);
        }
        break;
    case 15:
        {
            ::Windows::UI::Xaml::Controls::AppBarButton^ element15 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(element15))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::AppBarButton_Loaded);
        }
        break;
    case 18:
        {
            ::Windows::UI::Xaml::Documents::Hyperlink^ element18 = safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(__target);
            (safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(element18))->Click += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Documents::Hyperlink^, ::Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^>(this, (void (::Reddit::MyResources::*)
                (::Windows::UI::Xaml::Documents::Hyperlink^, ::Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^))&MyResources::username_click);
        }
        break;
    case 19:
        {
            ::Windows::UI::Xaml::Documents::Hyperlink^ element19 = safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(__target);
            (safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(element19))->Click += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Documents::Hyperlink^, ::Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^>(this, (void (::Reddit::MyResources::*)
                (::Windows::UI::Xaml::Documents::Hyperlink^, ::Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^))&MyResources::subreddit_click);
        }
        break;
    case 53:
        {
            ::Windows::UI::Xaml::Controls::AppBarToggleButton^ element53 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(element53))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::replyButton_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Reddit::MyResources::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 7: // MyResources.xaml line 201
            {
                ::Windows::UI::Xaml::Controls::Grid^ element7 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                MyResources_obj7_Bindings* objBindings = new MyResources_obj7_Bindings();
                objBindings->SetDataRoot(element7->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element7);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element7, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element7, bindings);
            }
            break;
        case 27: // MyResources.xaml line 152
            {
                ::Windows::UI::Xaml::Controls::Grid^ element27 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                MyResources_obj27_Bindings* objBindings = new MyResources_obj27_Bindings();
                objBindings->SetDataRoot(element27->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element27);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element27, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element27, bindings);
            }
            break;
        case 36: // MyResources.xaml line 116
            {
                ::Windows::UI::Xaml::Controls::Grid^ element36 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                MyResources_obj36_Bindings* objBindings = new MyResources_obj36_Bindings();
                objBindings->SetDataRoot(element36->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element36);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element36, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element36, bindings);
            }
            break;
        case 47: // MyResources.xaml line 65
            {
                ::Windows::UI::Xaml::Controls::Grid^ element47 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                MyResources_obj47_Bindings* objBindings = new MyResources_obj47_Bindings();
                objBindings->SetDataRoot(element47->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element47);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element47, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element47, bindings);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


