//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MyResources.xaml.h"

void ::Reddit::MyResources::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MyResources.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::MyResources::MyResources_obj2_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::account::subpostUWP, ::XamlBindingInfo::XamlBindingTrackingBase>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
public:
    MyResources_obj2_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~MyResources_obj2_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 2: // MyResources.xaml line 124
                this->obj2 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 3: // MyResources.xaml line 134
                this->obj3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                break;
            case 4: // MyResources.xaml line 136
                this->obj4 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 5: // MyResources.xaml line 138
                this->obj5 = safe_cast<::ExpanderControl::Expander^>(__target);
                break;
            case 7: // MyResources.xaml line 150
                this->obj7 = safe_cast<::Reddit::AppBarToggleColoredButton^>(__target);
                break;
            case 8: // MyResources.xaml line 156
                this->obj8 = safe_cast<::Reddit::AppBarToggleColoredButton^>(__target);
                break;
            case 9: // MyResources.xaml line 161
                this->obj9 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
                this->obj9->RegisterPropertyChangedCallback(::Windows::UI::Xaml::Controls::Primitives::ToggleButton::IsCheckedProperty,
                    ref new ::Windows::UI::Xaml::DependencyPropertyChangedCallback( 
                        [this] (::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                this->GetDataRoot()->saved = this->obj9->IsChecked ? this->obj9->IsChecked->Value : false;
                            }
                        }));
                break;
            case 11: // MyResources.xaml line 173
                this->obj11 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                break;
            case 12: // MyResources.xaml line 164
                this->obj12 = safe_cast<::Reddit::reportFlyout^>(__target);
                break;
            case 15: // MyResources.xaml line 147
                this->obj15 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 16: // MyResources.xaml line 145
                this->obj16 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 17: // MyResources.xaml line 145
                this->obj17 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 18: // MyResources.xaml line 142
                this->obj18 = safe_cast<::Reddit::EXplaceHolder^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        ReleaseAllListeners();
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::subpostUWP^>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj2.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::subpostUWP^) item, 1 << phase);
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::ResourceDictionary^ resources)
    {
        this->localResources = resources;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj2;
    ::Windows::UI::Xaml::Controls::Button^ obj3;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj4;
    ::ExpanderControl::Expander^ obj5;
    ::Reddit::AppBarToggleColoredButton^ obj7;
    ::Reddit::AppBarToggleColoredButton^ obj8;
    ::Windows::UI::Xaml::Controls::AppBarToggleButton^ obj9;
    ::Windows::UI::Xaml::Controls::AppBarButton^ obj11;
    ::Reddit::reportFlyout^ obj12;
    ::Windows::UI::Xaml::Documents::Run^ obj15;
    ::Windows::UI::Xaml::Documents::Run^ obj16;
    ::Windows::UI::Xaml::Documents::Run^ obj17;
    ::Reddit::EXplaceHolder^ obj18;
    
    // Fields for binding tracking.
    ::Platform::WeakReference cachePC_;
    ::Windows::Foundation::EventRegistrationToken tokenPC_;

    // Update methods for each path node used in binding steps.
    void Update_(::account::subpostUWP^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, this->cachePC_, &tokenPC_);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_thumbnail(obj->thumbnail, phase);
                this->Update_previewCommand(obj->previewCommand, phase);
                this->Update_Title(obj->Title, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_contentType(obj->contentType, phase);
                this->Update_Liked(obj->Liked, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changeupvote(obj->changeupvote, phase);
                this->Update_changedownvote(obj->changedownvote, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_saved(obj->saved, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_subreddit(obj->subreddit, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_score(obj->score, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_author(obj->author, phase);
            }
        }
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 173
            Set_Windows_UI_Xaml_FrameworkElement_DataContext(this->obj11, obj, nullptr);
            // MyResources.xaml line 142
            Set_Reddit_EXplaceHolder_post(this->obj18, obj, nullptr);
        }
    }
    void Update_thumbnail(::Windows::UI::Xaml::FrameworkElement^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 134
            Set_Windows_UI_Xaml_Controls_ContentControl_Content(this->obj3, obj, nullptr);
        }
    }
    void Update_previewCommand(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 134
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj3, obj, nullptr);
        }
    }
    void Update_Title(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 136
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj4, obj, nullptr);
        }
    }
    void Update_contentType(::account::postContentType obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 138
            Set_Windows_UI_Xaml_UIElement_Visibility(this->obj5, safe_cast<::Windows::UI::Xaml::Visibility>(this->LookupConverter("prevConv")->Convert(obj, ::Windows::UI::Xaml::Visibility::typeid, "self", nullptr)));
        }
    }
    void Update_Liked(::Platform::IBox<::Platform::Boolean>^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 150
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj7, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("upvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
            // MyResources.xaml line 156
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj8, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("downvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_changeupvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 150
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj7, obj, nullptr);
        }
    }
    void Update_changedownvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 156
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj8, obj, nullptr);
        }
    }
    void Update_saved(::Platform::Boolean obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 161
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj9, obj, nullptr);
        }
    }
    void Update_subreddit(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 164
            Set_Reddit_reportFlyout_subreddit(this->obj12, obj, nullptr);
            // MyResources.xaml line 145
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj16, obj, nullptr);
        }
    }
    void Update_score(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 147
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj15, safe_cast<::Platform::String^>(this->LookupConverter("scoreVis")->Convert(obj, ::Platform::String::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_author(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 145
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj17, obj, nullptr);
        }
    }

    virtual void ReleaseAllListeners() override
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, this->cachePC_, &tokenPC_);
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
        if (this->GetDataRoot() != nullptr && this->GetDataRoot()->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::account::subpostUWP^ obj = safe_cast<::account::subpostUWP^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_contentType(obj->contentType, DATA_CHANGED);
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                    this->Update_saved(obj->saved, DATA_CHANGED);
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
            else if (propName == "contentType")
            {
                if (obj != nullptr)
                {
                    this->Update_contentType(obj->contentType, DATA_CHANGED);
                }
            }
            else if (propName == "Liked")
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                }
            }
            else if (propName == "saved")
            {
                if (obj != nullptr)
                {
                    this->Update_saved(obj->saved, DATA_CHANGED);
                }
            }
            else if (propName == "score")
            {
                if (obj != nullptr)
                {
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
        }
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }
    static void Set_Windows_UI_Xaml_Controls_ContentControl_Content(::Windows::UI::Xaml::Controls::ContentControl^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->Content = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(::Windows::UI::Xaml::Controls::Primitives::ButtonBase^ obj, ::Windows::UI::Xaml::Input::ICommand^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Input::ICommand^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Input::ICommand::typeid, targetNullValue);
        }
        obj->Command = value;
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_UIElement_Visibility(::Windows::UI::Xaml::UIElement^ obj, ::Windows::UI::Xaml::Visibility value)
    {
        obj->Visibility = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ obj, ::Platform::IBox<::Platform::Boolean>^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::IBox<::Platform::Boolean>^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::IBox<::Platform::Boolean>::typeid, targetNullValue);
        }
        obj->IsChecked = value;
    }
    static void Set_Windows_UI_Xaml_FrameworkElement_DataContext(::Windows::UI::Xaml::FrameworkElement^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->DataContext = value;
    }
    static void Set_Reddit_reportFlyout_subreddit(::Reddit::reportFlyout^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->subreddit = value;
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Reddit_EXplaceHolder_post(::Reddit::EXplaceHolder^ obj, ::account::subpostUWP^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::account::subpostUWP^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::account::subpostUWP::typeid, targetNullValue);
        }
        obj->post = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::MyResources::MyResources_obj19_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::account::subpostUWP, ::XamlBindingInfo::XamlBindingTrackingBase>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
public:
    MyResources_obj19_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~MyResources_obj19_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 19: // MyResources.xaml line 75
                this->obj19 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 20: // MyResources.xaml line 81
                this->obj20 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 21: // MyResources.xaml line 82
                this->obj21 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 22: // MyResources.xaml line 113
                this->obj22 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 23: // MyResources.xaml line 117
                this->obj23 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 24: // MyResources.xaml line 87
                this->obj24 = safe_cast<::Reddit::NoToggleBehaviorButton^>(__target);
                break;
            case 25: // MyResources.xaml line 99
                this->obj25 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 26: // MyResources.xaml line 100
                this->obj26 = safe_cast<::Reddit::NoToggleBehaviorButton^>(__target);
                break;
            case 27: // MyResources.xaml line 84
                this->obj27 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        ReleaseAllListeners();
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::subpostUWP^>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj19.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::subpostUWP^) item, 1 << phase);
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::ResourceDictionary^ resources)
    {
        this->localResources = resources;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj19;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj20;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj21;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj22;
    ::Windows::UI::Xaml::Documents::Run^ obj23;
    ::Reddit::NoToggleBehaviorButton^ obj24;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj25;
    ::Reddit::NoToggleBehaviorButton^ obj26;
    ::Windows::UI::Xaml::Documents::Run^ obj27;
    
    // Fields for binding tracking.
    ::Platform::WeakReference cachePC_;
    ::Windows::Foundation::EventRegistrationToken tokenPC_;

    // Update methods for each path node used in binding steps.
    void Update_(::account::subpostUWP^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, this->cachePC_, &tokenPC_);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Title(obj->Title, phase);
                this->Update_author(obj->author, phase);
                this->Update_selftext(obj->selftext, phase);
                this->Update_num_comments(obj->num_comments, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Liked(obj->Liked, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changeupvote(obj->changeupvote, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_score(obj->score, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changedownvote(obj->changedownvote, phase);
                this->Update_subreddit(obj->subreddit, phase);
            }
        }
    }
    void Update_Title(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 81
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj20, obj, nullptr);
        }
    }
    void Update_author(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 82
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj21, obj, nullptr);
        }
    }
    void Update_selftext(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 113
            Set_mdblock_mdRichProperties_MD(this->obj22, obj, nullptr);
        }
    }
    void Update_num_comments(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 117
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj23, obj.ToString(), nullptr);
        }
    }
    void Update_Liked(::Platform::IBox<::Platform::Boolean>^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 87
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj24, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("upvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
            // MyResources.xaml line 100
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj26, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("downvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_changeupvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 87
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj24, obj, nullptr);
        }
    }
    void Update_score(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 99
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj25, obj.ToString(), nullptr);
        }
    }
    void Update_changedownvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 100
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj26, obj, nullptr);
        }
    }
    void Update_subreddit(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 84
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj27, obj, nullptr);
        }
    }

    virtual void ReleaseAllListeners() override
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, this->cachePC_, &tokenPC_);
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
        if (this->GetDataRoot() != nullptr && this->GetDataRoot()->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::account::subpostUWP^ obj = safe_cast<::account::subpostUWP^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
            else if (propName == "Liked")
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                }
            }
            else if (propName == "score")
            {
                if (obj != nullptr)
                {
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
        }
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_mdblock_mdRichProperties_MD(::Windows::UI::Xaml::FrameworkElement^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        ::mdblock::mdRichProperties::SetMD(obj, value);
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ obj, ::Platform::IBox<::Platform::Boolean>^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::IBox<::Platform::Boolean>^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::IBox<::Platform::Boolean>::typeid, targetNullValue);
        }
        obj->IsChecked = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(::Windows::UI::Xaml::Controls::Primitives::ButtonBase^ obj, ::Windows::UI::Xaml::Input::ICommand^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Input::ICommand^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Input::ICommand::typeid, targetNullValue);
        }
        obj->Command = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::MyResources::MyResources_obj28_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::account::subpostUWP, ::XamlBindingInfo::XamlBindingTrackingBase>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
public:
    MyResources_obj28_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~MyResources_obj28_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 28: // MyResources.xaml line 36
                this->obj28 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 29: // MyResources.xaml line 42
                this->obj29 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 30: // MyResources.xaml line 43
                this->obj30 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 31: // MyResources.xaml line 52
                this->obj31 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                break;
            case 32: // MyResources.xaml line 65
                this->obj32 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 33: // MyResources.xaml line 59
                this->obj33 = safe_cast<::Windows::UI::Xaml::Shapes::Path^>(__target);
                break;
            case 34: // MyResources.xaml line 56
                this->obj34 = safe_cast<::Windows::UI::Xaml::Media::Imaging::BitmapImage^>(__target);
                break;
            case 35: // MyResources.xaml line 48
                this->obj35 = safe_cast<::Reddit::NoToggleBehaviorButton^>(__target);
                break;
            case 36: // MyResources.xaml line 49
                this->obj36 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 37: // MyResources.xaml line 50
                this->obj37 = safe_cast<::Reddit::NoToggleBehaviorButton^>(__target);
                break;
            case 38: // MyResources.xaml line 45
                this->obj38 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        ReleaseAllListeners();
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::subpostUWP^>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj28.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::subpostUWP^) item, 1 << phase);
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::ResourceDictionary^ resources)
    {
        this->localResources = resources;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj28;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj29;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj30;
    ::Windows::UI::Xaml::Controls::Button^ obj31;
    ::Windows::UI::Xaml::Documents::Run^ obj32;
    ::Windows::UI::Xaml::Shapes::Path^ obj33;
    ::Windows::UI::Xaml::Media::Imaging::BitmapImage^ obj34;
    ::Reddit::NoToggleBehaviorButton^ obj35;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj36;
    ::Reddit::NoToggleBehaviorButton^ obj37;
    ::Windows::UI::Xaml::Documents::Run^ obj38;
    
    // Fields for binding tracking.
    ::Platform::WeakReference cachePC_;
    ::Windows::Foundation::EventRegistrationToken tokenPC_;

    // Update methods for each path node used in binding steps.
    void Update_(::account::subpostUWP^ obj, int phase)
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(obj, this->cachePC_, &tokenPC_);
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Title(obj->Title, phase);
                this->Update_author(obj->author, phase);
                this->Update_previewCommand(obj->previewCommand, phase);
                this->Update_num_comments(obj->num_comments, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_contentType(obj->contentType, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_previewURI(obj->previewURI, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Liked(obj->Liked, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changeupvote(obj->changeupvote, phase);
            }
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_score(obj->score, phase);
            }
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_changedownvote(obj->changedownvote, phase);
                this->Update_subreddit(obj->subreddit, phase);
            }
        }
    }
    void Update_Title(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 42
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj29, obj, nullptr);
        }
    }
    void Update_author(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 43
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj30, obj, nullptr);
        }
    }
    void Update_previewCommand(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 52
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj31, obj, nullptr);
        }
    }
    void Update_num_comments(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 65
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj32, obj.ToString(), nullptr);
        }
    }
    void Update_contentType(::account::postContentType obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 59
            Set_Windows_UI_Xaml_Shapes_Path_Data(this->obj33, safe_cast<::Windows::UI::Xaml::Media::Geometry^>(this->LookupConverter("pathdataconvz")->Convert(obj, ::Windows::UI::Xaml::Media::Geometry::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_previewURI(::Windows::Foundation::Uri^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 56
            Set_Windows_UI_Xaml_Media_Imaging_BitmapImage_UriSource(this->obj34, obj, nullptr);
        }
    }
    void Update_Liked(::Platform::IBox<::Platform::Boolean>^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 48
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj35, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("upvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
            // MyResources.xaml line 50
            Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(this->obj37, safe_cast<::Platform::IBox<::Platform::Boolean>^>(this->LookupConverter("downvoteconvert")->Convert(obj, ::Platform::IBox<::Platform::Boolean>::typeid, nullptr, nullptr)), nullptr);
        }
    }
    void Update_changeupvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 48
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj35, obj, nullptr);
        }
    }
    void Update_score(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // MyResources.xaml line 49
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj36, obj.ToString(), nullptr);
        }
    }
    void Update_changedownvote(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 50
            Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(this->obj37, obj, nullptr);
        }
    }
    void Update_subreddit(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // MyResources.xaml line 45
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj38, obj, nullptr);
        }
    }

    virtual void ReleaseAllListeners() override
    {
        this->_bindingsTracking->UpdatePropertyChangedListener(nullptr, this->cachePC_, &tokenPC_);
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
        if (this->GetDataRoot() != nullptr && this->GetDataRoot()->Equals(sender))
        {
            ::Platform::String^ propName = e->PropertyName;
            ::account::subpostUWP^ obj = safe_cast<::account::subpostUWP^>(sender);
            if (propName == nullptr || propName->IsEmpty())
            {
                if (obj != nullptr)
                {
                    this->Update_contentType(obj->contentType, DATA_CHANGED);
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
            else if (propName == "contentType")
            {
                if (obj != nullptr)
                {
                    this->Update_contentType(obj->contentType, DATA_CHANGED);
                }
            }
            else if (propName == "Liked")
            {
                if (obj != nullptr)
                {
                    this->Update_Liked(obj->Liked, DATA_CHANGED);
                }
            }
            else if (propName == "score")
            {
                if (obj != nullptr)
                {
                    this->Update_score(obj->score, DATA_CHANGED);
                }
            }
        }
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ButtonBase_Command(::Windows::UI::Xaml::Controls::Primitives::ButtonBase^ obj, ::Windows::UI::Xaml::Input::ICommand^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Input::ICommand^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Input::ICommand::typeid, targetNullValue);
        }
        obj->Command = value;
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Shapes_Path_Data(::Windows::UI::Xaml::Shapes::Path^ obj, ::Windows::UI::Xaml::Media::Geometry^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Media::Geometry^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::Geometry::typeid, targetNullValue);
        }
        obj->Data = value;
    }
    static void Set_Windows_UI_Xaml_Media_Imaging_BitmapImage_UriSource(::Windows::UI::Xaml::Media::Imaging::BitmapImage^ obj, ::Windows::Foundation::Uri^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::Foundation::Uri^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::Foundation::Uri::typeid, targetNullValue);
        }
        obj->UriSource = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Primitives_ToggleButton_IsChecked(::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ obj, ::Platform::IBox<::Platform::Boolean>^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::IBox<::Platform::Boolean>^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::IBox<::Platform::Boolean>::typeid, targetNullValue);
        }
        obj->IsChecked = value;
    }
};

void ::Reddit::MyResources::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            this->listSelfPost = safe_cast<::Windows::UI::Xaml::DataTemplate^>(__target);
        }
        break;
    case 5:
        {
            ::ExpanderControl::Expander^ element5 = safe_cast<::ExpanderControl::Expander^>(__target);
            (safe_cast<::ExpanderControl::Expander^>(element5))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::contentExpander_Loading);
        }
        break;
    case 6:
        {
            ::Windows::UI::Xaml::Controls::TextBlock^ element6 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(element6))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::TextBlock_Loaded);
        }
        break;
    case 10:
        {
            ::Windows::UI::Xaml::Controls::AppBarToggleButton^ element10 = safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarToggleButton^>(element10))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::replyButton_Click);
        }
        break;
    case 11:
        {
            ::Windows::UI::Xaml::Controls::AppBarButton^ element11 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(element11))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::MyResources::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MyResources::AppBarButton_Loaded);
        }
        break;
    case 13:
        {
            ::Windows::UI::Xaml::Documents::Hyperlink^ element13 = safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(__target);
            (safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(element13))->Click += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Documents::Hyperlink^, ::Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^>(this, (void (::Reddit::MyResources::*)
                (::Windows::UI::Xaml::Documents::Hyperlink^, ::Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^))&MyResources::username_click);
        }
        break;
    case 14:
        {
            ::Windows::UI::Xaml::Documents::Hyperlink^ element14 = safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(__target);
            (safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(element14))->Click += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Documents::Hyperlink^, ::Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^>(this, (void (::Reddit::MyResources::*)
                (::Windows::UI::Xaml::Documents::Hyperlink^, ::Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^))&MyResources::subreddit_click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Reddit::MyResources::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 2: // MyResources.xaml line 124
            {
                ::Windows::UI::Xaml::Controls::Grid^ element2 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                MyResources_obj2_Bindings* objBindings = new MyResources_obj2_Bindings();
                objBindings->SetDataRoot(element2->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element2);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element2, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element2, bindings);
            }
            break;
        case 19: // MyResources.xaml line 75
            {
                ::Windows::UI::Xaml::Controls::Grid^ element19 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                MyResources_obj19_Bindings* objBindings = new MyResources_obj19_Bindings();
                objBindings->SetDataRoot(element19->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element19);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element19, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element19, bindings);
            }
            break;
        case 28: // MyResources.xaml line 36
            {
                ::Windows::UI::Xaml::Controls::Grid^ element28 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                MyResources_obj28_Bindings* objBindings = new MyResources_obj28_Bindings();
                objBindings->SetDataRoot(element28->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element28);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element28, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element28, bindings);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


