//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "rootWindowGrid.xaml.h"

void ::Reddit::rootWindowGrid::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///rootWindowGrid.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::rootWindowGrid::rootWindowGrid_obj6_Bindings 
    : public ::XamlBindingInfo::ValueTypeXamlBindings<::account::subredditInfo, ::XamlBindingInfo::XamlBindingTrackingBase>
{
public:
    rootWindowGrid_obj6_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 6: // rootWindowGrid.xaml line 78
                this->obj6 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 7: // rootWindowGrid.xaml line 87
                this->obj7 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 8: // rootWindowGrid.xaml line 89
                this->obj8 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::subredditInfo>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj6.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::subredditInfo) item, 1 << phase);
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj6;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj7;
    ::Windows::UI::Xaml::Documents::Run^ obj8;

    // Update methods for each path node used in binding steps.
    void Update_(::account::subredditInfo obj, int phase)
    {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_pname(obj.pname, phase);
                this->Update_subscribers(obj.subscribers, phase);
            }
    }
    void Update_pname(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // rootWindowGrid.xaml line 87
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj7, obj, nullptr);
        }
    }
    void Update_subscribers(::default::uint32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // rootWindowGrid.xaml line 89
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj8, obj.ToString(), nullptr);
        }
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::rootWindowGrid::rootWindowGrid_obj10_Bindings 
    : public ::XamlBindingInfo::ValueTypeXamlBindings<::account::AccountInfo, ::XamlBindingInfo::XamlBindingTrackingBase>
{
public:
    rootWindowGrid_obj10_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 10: // rootWindowGrid.xaml line 29
                this->obj10 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 11: // rootWindowGrid.xaml line 39
                this->obj11 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 12: // rootWindowGrid.xaml line 42
                this->obj12 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 13: // rootWindowGrid.xaml line 42
                this->obj13 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::AccountInfo>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj10.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::AccountInfo) item, 1 << phase);
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj10;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj11;
    ::Windows::UI::Xaml::Documents::Run^ obj12;
    ::Windows::UI::Xaml::Documents::Run^ obj13;

    // Update methods for each path node used in binding steps.
    void Update_(::account::AccountInfo obj, int phase)
    {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_username(obj.username, phase);
                this->Update_comment_karma(obj.comment_karma, phase);
                this->Update_link_karma(obj.link_karma, phase);
            }
    }
    void Update_username(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // rootWindowGrid.xaml line 39
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj11, obj, nullptr);
        }
    }
    void Update_comment_karma(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // rootWindowGrid.xaml line 42
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj12, obj.ToString(), nullptr);
        }
    }
    void Update_link_karma(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // rootWindowGrid.xaml line 42
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj13, obj.ToString(), nullptr);
        }
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Reddit::rootWindowGrid::rootWindowGrid_obj14_Bindings 
    : public ::XamlBindingInfo::ValueTypeXamlBindings<::account::AccountInfo, ::XamlBindingInfo::XamlBindingTrackingBase>
{
public:
    rootWindowGrid_obj14_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 14: // rootWindowGrid.xaml line 50
                this->obj14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 15: // rootWindowGrid.xaml line 51
                this->obj15 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 16: // rootWindowGrid.xaml line 51
                this->obj16 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 17: // rootWindowGrid.xaml line 51
                this->obj17 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::account::AccountInfo>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj14.Resolve<::Windows::UI::Xaml::Controls::TextBlock>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::account::AccountInfo) item, 1 << phase);
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj14;
    ::Windows::UI::Xaml::Documents::Run^ obj15;
    ::Windows::UI::Xaml::Documents::Run^ obj16;
    ::Windows::UI::Xaml::Documents::Run^ obj17;

    // Update methods for each path node used in binding steps.
    void Update_(::account::AccountInfo obj, int phase)
    {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_username(obj.username, phase);
                this->Update_link_karma(obj.link_karma, phase);
                this->Update_comment_karma(obj.comment_karma, phase);
            }
    }
    void Update_username(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // rootWindowGrid.xaml line 51
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj15, obj, nullptr);
        }
    }
    void Update_link_karma(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // rootWindowGrid.xaml line 51
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj16, obj.ToString(), nullptr);
        }
    }
    void Update_comment_karma(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // rootWindowGrid.xaml line 51
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj17, obj.ToString(), nullptr);
        }
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
};

void ::Reddit::rootWindowGrid::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            this->titleRowDef = safe_cast<::Windows::UI::Xaml::Controls::RowDefinition^>(__target);
        }
        break;
    case 2:
        {
            this->titleGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->rootFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Frame^>(this->rootFrame))->Navigated += ref new ::Windows::UI::Xaml::Navigation::NavigatedEventHandler(this, (void (::Reddit::rootWindowGrid::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Navigation::NavigationEventArgs^))&rootWindowGrid::rootFrame_Navigated);
        }
        break;
    case 4:
        {
            this->titleRec = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
        }
        break;
    case 5:
        {
            this->searchBox = safe_cast<::Windows::UI::Xaml::Controls::AutoSuggestBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AutoSuggestBox^>(this->searchBox))->TextChanged += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::AutoSuggestBox^, ::Windows::UI::Xaml::Controls::AutoSuggestBoxTextChangedEventArgs^>(this, (void (::Reddit::rootWindowGrid::*)
                (::Windows::UI::Xaml::Controls::AutoSuggestBox^, ::Windows::UI::Xaml::Controls::AutoSuggestBoxTextChangedEventArgs^))&rootWindowGrid::AutoSuggestBox_TextChanged);
            (safe_cast<::Windows::UI::Xaml::Controls::AutoSuggestBox^>(this->searchBox))->QuerySubmitted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::AutoSuggestBox^, ::Windows::UI::Xaml::Controls::AutoSuggestBoxQuerySubmittedEventArgs^>(this, (void (::Reddit::rootWindowGrid::*)
                (::Windows::UI::Xaml::Controls::AutoSuggestBox^, ::Windows::UI::Xaml::Controls::AutoSuggestBoxQuerySubmittedEventArgs^))&rootWindowGrid::AutoSuggestBox_QuerySubmitted);
        }
        break;
    case 9:
        {
            this->accountBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->accountBox))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Reddit::rootWindowGrid::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&rootWindowGrid::Grid_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->accountBox))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Reddit::rootWindowGrid::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&rootWindowGrid::ComboBox_SelectionChanged);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Reddit::rootWindowGrid::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 6: // rootWindowGrid.xaml line 78
            {
                ::Windows::UI::Xaml::Controls::Grid^ element6 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                rootWindowGrid_obj6_Bindings* objBindings = new rootWindowGrid_obj6_Bindings();
                objBindings->SetDataRoot(element6->DataContext);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element6);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element6, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element6, bindings);
            }
            break;
        case 10: // rootWindowGrid.xaml line 29
            {
                ::Windows::UI::Xaml::Controls::Grid^ element10 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                rootWindowGrid_obj10_Bindings* objBindings = new rootWindowGrid_obj10_Bindings();
                objBindings->SetDataRoot(element10->DataContext);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element10);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element10, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element10, bindings);
            }
            break;
        case 14: // rootWindowGrid.xaml line 50
            {
                ::Windows::UI::Xaml::Controls::TextBlock^ element14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                rootWindowGrid_obj14_Bindings* objBindings = new rootWindowGrid_obj14_Bindings();
                objBindings->SetDataRoot(element14->DataContext);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element14);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element14, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element14, bindings);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


